### ISSUE TITLE
Fix Problem Statement

### ISSUE THREAD

**Issue by Maryamvalian** [Maryamvalian/project741#1]
@smiths please check my problem statement.

**Comment by smiths** [comment]
Me feedback is as follows:

- please provide a link to the problem statement in the issue (for future issues)
- please explicitly assign the issue to me (for future issues)
- please update `Repos.csv` with your information
- for the problem statement, please add a few references.  In particular, it would be nice if you could find an online truss analysis tool that you can point to as an example
- for the outputs in Section 1.2, please also mention the support reactions
- for goal 1, please change the mention of stress distribution to force distribution.  I'm being a bit picky, but I don't think you will worry about stresses, since that requires information on the cross-sectional area of each member.

In your SRS you will have to think about how to characterize the input that describes a general truss.  You can find an example of a specific truss done for 741 in Drasil [here](https://github.com/tingyuw/cas741/blob/master/docs/SRS/SRS.pdf).  This example is for a fixed geometry.  For your project, we really should have the capability of specifying different trusses.  That is why I suggested that you find some online calculators that should give an idea of how this information is specified by others.

I'll change the assignment of the issue to you.  Once you have done the above, please reassign the issue to me, or create a new issue.  Once the changes are made, I'll approve the project.

**Comment by Maryamvalian** [comment]
fixed problem statement
[https://github.com/Maryamvalian/project741/tree/main/docs/ProblemStatementAndGoals](url)

**Comment by Maryamvalian** [comment]
@smiths I have updated my details in repos.csv file. Please check and approve it.

**Comment by smiths** [comment]
Thank you @Maryamvalian.  Your problem statement is now approved.  :smile:
