### ISSUE TITLE
VnV Plan 5.1: Table 1 Brackets

### ISSUE THREAD

**Issue by LesleyWheat** [Maryamvalian/project741#19]
All the items in the F column are {()} and then you have another column named {S(p,r)}. I'm not sure why you have those double brackets. If F is supposed to be a set {(),(),...} then why are there no inputs with more than one item?

**Comment by Maryamvalian** [comment]
I appreciate your comment, but in section 5.1 the goal of test cases is to measure run-time based on the number of joints. So the other variables are held the same to avoid their effect. Otherwise, the external force can be a set of different forces. but in this section, there is only one force for all of the test cases
