### ISSUE TITLE
MIS: Export Access Programs are not included in Access Routine Semantics

### ISSUE THREAD

**Issue by LesleyWheat** [Maryamvalian/project741#37]
This is an issue for many modules but I'm just going to use Input Module as an example.

Input module
Load-Parameter()
Should this function not return n, m, J, etc... ? Also, how are load_params and verify_params not access programs?

Exported Access Program "Inputs" says it has the output of "Parameters" but parameters is never defined.

What is this table for? (also goes for all the other modules)
![image](https://user-images.githubusercontent.com/29044132/226684852-8c230d81-56b7-4955-9edf-c5d52eee329f.png)

**Comment by Maryamvalian** [comment]
I used this table to define the output parameters for the input module. The input module has two modules: load_param and verify_params. load_params reads parameters from the file and verify_params checks the constraints and creates an exception if bad input.  Otherwise, the Input module will output the correct parameters listed in the table. . it is a little bit confusing for me, I will wait for other feedback and then decide to change this part. Thank you for your time and comments, Lesley!
